### ISSUE TITLE
Remove AndroidImageSlidder becuase it depends on a deprecated library

### ISSUE THREAD

**Issue by bubunyo** [RbkGh/Android-Libraries-Top-50#1]
The AndroidImageSlider library should be removed from the list because it depends on a deprecated library; NineOldAndroid.

**Comment by RbkGh** [comment]
Sure,valid point! Removed here #6600151e986172a5f4812a7ff1345a55e54cd57f

**Comment by RbkGh** [comment]
Sure,valid point! Removed here https://github.com/RbkGh/Android-Libraries-Top-50/commit/6600151e986172a5f4812a7ff1345a55e54cd57f
